### ISSUE TITLE
Unable to update preCICE version

### ISSUE THREAD

**Issue by carme-hp** [maierbn/opendihu#11]
OpenDiHu creates a private installation of preCICE 2.1.0, which is obsolete. To check what is the precice version installed, just run any case that uses precice and you will get information about the version in the preCICE logging. 

As far as I know, the link to download precice is found in this [file](https://github.com/maierbn/opendihu/blob/develop/dependencies/scons-config/sconsconfig/packages/precice.py), and it indeed points to the 2.1.0 version. I change the link for one that points to the last release (version 2.5): https://github.com/precice/precice/archive/refs/tags/v2.5.0.zip

I have deleted my installation and then
- downloaded OpenDiHu
- replace link in  [file](https://github.com/maierbn/opendihu/blob/develop/dependencies/scons-config/sconsconfig/packages/precice.py)
- run `make`

But then I see that the 2.1.0 zip file is downloaded so I stop the installation. This makes me think that this is not the file where the downloading link is defined, but I don't see any other file that contains the link. For debugging purposes, I also tried to modify the message "Downloading..." and I couldn't, which again confirms the idea that I'm not looking at the right files. 

Any idea where to look?

**Comment by qres** [comment]
After changes to files in the `sconsconfig` folder you have to repack the python `opendihu/dependencies/scons-config/dist/scons_config-0.1-py3.6.egg` file. This is the actual file that is read during the scons run. You can update the file with
```bash
cd opendihu/dependencies/scons-config
bash install_manually.sh
```
The `egg` is just a zip file, so you can also check its contents.
