### ISSUE TITLE
Unable to use preCICE v2.5

### ISSUE THREAD

**Issue by carme-hp** [maierbn/opendihu#12]
OpenDiHu installs it's own precice enviroment with version 2.1. However, version 2.1 is obsolete and needs to be updated to 2.5

Therefore the file [precice.py](https://github.com/maierbn/opendihu/blob/develop/dependencies/scons-config/sconsconfig/packages/precice.py) needs to be modified:
- update link to download precice:
```
def __init__(self, **kwargs):
    defaults = {
        'download_url': 'https://github.com/precice/precice/archive/refs/tags/v2.5.0.zip',
    }
```
- update precice dependency boost from 1.65.1 to most recent one 1.81.0:
```
  # boost
  'cd ${SOURCE_DIR} && if [ ! -f ${SOURCE_DIR}/boost_1_81_0.tar.gz ] && \
    ( wget https://boostorg.jfrog.io/artifactory/main/release/1.81.0/source/boost_1_81_0.tar.gz && tar xf boost_1_81_0.tar.gz ); \
    cd boost_1_81_0 && ./bootstrap.sh --with-libraries=log,thread,system,filesystem,program_options,unit_test_framework --prefix=${PREFIX} && \
    ./b2 -j12 install',
```

**Important:** after modifying `precice.py` it's necessary to run (see #11):
```
cd opendihu/dependencies/scons-config
bash install_manually.sh
```

All I get in terminal is the following message
> Installation of preCICE failed. Often, the problem is that boost is not installed. Install boost with sudo apt install libboost-all-dev
> Then rebuild with make clean; scons PRECICE_REBUILD=True

Is there a file where I can see more detailed error messages?

About the possible errors, I suspect that it could be that I'm not including the dependencies correctly. I'm using what is in branch develop and I have tried playing a bit with how I include the root folders but so far unsuccessfully.  Also something that looks weird to me is that at the documentation of precice I see the following:
> The directory you chose as prefix now contains libraries in <prefix>/lib and the all the Boost headers in <prefix>/include. You may now safely remove the boost directory from step 1

Yet my boost folder doesn't have an include/ folder.

**Comment by maierbn** [comment]
> Is there a file where I can see more detailed error messages?

The file `config.log` contains all stdout output during installation. You can also try to manually execute all relevant bash commands in [precice.py](https://github.com/maierbn/opendihu/blob/develop/dependencies/scons-config/sconsconfig/packages/precice.py) in a temporary folder to see what is going on.

**Comment by carme-hp** [comment]
Perfect, thanks :pray:

**Comment by carme-hp** [comment]
It was possible to install precice 2.5 on an ubuntu 22.04 laptop. The trick was to use the petsc installation of the system directly. The changes can be seen on this  [branch](https://github.com/maierbn/opendihu/tree/update-precice-v2.5)
