### ISSUE TITLE
Scaling issue in the transfer of traction

### ISSUE THREAD

**Issue by carme-hp** [maierbn/opendihu#15]
This question is motivated  by the mechanical coupling between muscle and tendon. 

In the precice surface adapter, we can exchange the *traction* between the two participants. To be specific, *traction* refers to the `materialTraction_` in the hyperelasticity solver.  The material traction is computed as follows:

[materialTraction = pK2Stress * materialNormal](https://github.com/maierbn/opendihu/blob/develop/core/src/specialized_solver/solid_mechanics/hyperelasticity/01_material_computations_stress.tpp#L673)

where *pK2Stress* is a  3x3 matrix and the *materialNormal* is a normalized 3x1 vector. 
My general understanding is that *traction* refers to a force, whereas *stress* refers to force by area. But this is not true here, as by this definition of the traction, the traction is also depending on the area. 

**That the traction depends on the area makes the mechanical coupling complicated and leads to a scaling issue in the precice adapter**.  

To illustrate the issue I consider a simple muscle-tendon case that uses an explicit coupling scheme and `dt_coupling = dt_mechanics_solver = 0.01` and a matching mesh. The setup is the following:
![muscle_tendon](https://user-images.githubusercontent.com/71499004/226563094-3e6cc6c0-001f-4bb6-a5ee-de0f90fea549.png)

- case A

 ```
muscle1_extent = [3.0, 3.0, 14.8] 
n_elements_muscle1 = [2, 2, 20] 
tendon_extent = [3.0, 3.0, 2.0] 
tendon_offset = [0.0, 0.0, muscle1_extent[2]]
n_elements_tendon = [2, 2, 4] 

```

-  case B

 ```
muscle1_extent = [3.0, 3.0, 14.8] 
n_elements_muscle1 = [2, 2, 20] 
tendon_extent = [3.0, 3.0, 2.96] # modified length
tendon_offset = [0.0, 0.0, muscle1_extent[2]]
n_elements_tendon = [2, 2, 4] 

```

First I look at case A and I see what happens if I change 

 ```

n_elements_muscle1 = [4, 4, 40] 
n_elements_tendon = [4, 4, 8] 

```

![elements](https://user-images.githubusercontent.com/71499004/226419567-d05de57b-16f0-4135-a546-74d1933c4f95.png)

We can see how the traction is clearly affected by the resolution of the 3D mesh. I have checked that `materialTraction_` is indeed what is being written to precice and that the `materialNormal = (0,0,1)`.

Now we look at the results of the traction not only at the muscle solver but also at the tendon solver. Note that the traction has opposite signs and the absolute value has been taken. What I would like to see in the plot of the traction is that the traction is the same in the muscle and the tendon.

 For case A I have:
![caseA](https://user-images.githubusercontent.com/71499004/226424268-646f986c-620d-43af-ad6c-81cb8ce32100.png)

This is not matching as it should. However in case A we have that the volume of each element  of the muscle mesh is 1.5x1.5x0.74 = 1.665 , whereas in the tendon mesh is 1.5x1.5x0.5 = 1.125. Therefore I try case B, where the tendon length has been changed to match the mesh resolution of the muscle.   
![caseB](https://user-images.githubusercontent.com/71499004/226424396-2ea3ef95-3297-4038-852c-f2bec5766d64.png)

I don't have an explanation why it doesn't match in case B. I have check that the values that the muscle writes to precice are the same that the tendon reads from precice. 

And if we put the two cases together : 
![bothcases](https://user-images.githubusercontent.com/71499004/226424598-f947685a-2f6e-4cea-897b-34a08e035191.png)

All in all, we have that there is a scaling issue due to 
- the fact the traction depends on the mesh resolution
- another scaling factor whose nature  is still unknown to me (what we see in case B)

@maierbn does this make sense to you or am I understanding traction wrongly? Do you have any idea how to work around the first point and/or ideas for the second point?

**Comment by carme-hp** [comment]
I checked whether the scaling issues for the traction in the tendon are present when I set the traction via a neumann BC. The exact setup can be seen in this [commit](https://github.com/maierbn/opendihu/commit/fb61cce8bffb43b71dcca7a9a31b762cec57b185). 

For this I consider a single tendon (no coupling). I use the following bc inspired by the results from the muscle:

![bc](https://user-images.githubusercontent.com/71499004/226609932-4487af1f-bce8-4b55-8f6d-371dea3785e8.png)

And then I compare the bc with the traction values at the surface:

![bc_tendon](https://user-images.githubusercontent.com/71499004/226610191-5924cc00-65dc-43b7-a110-ed2557842d2d.png)

In this case, **no scaling issues are present**.

**Comment by carme-hp** [comment]
Actually, if I'm only interested that the z values of traction are preserved at the interface, I can work around the scaling issue. To do so, I just have to transfer the values of z and write 0s in the other components in `02_read_write.tpp`:
```
            Vec3 traction;
            // for (int i = 0; i < 3; i++)
            // {
            //   traction[i] = tractionValues_[3*valueIndex + i];
            // }

            traction[0] = 0;
            traction[1] = 0;
            traction[2] = tractionValues_[3*valueIndex + 2];
```

See the results if both participants have the exact same resolution:
![onlyz_caseB](https://user-images.githubusercontent.com/71499004/227254552-df45f0b0-30bd-4957-9d7d-06f10ac698b5.png)

And the comparison with a case where they don't:
![onlyz](https://user-images.githubusercontent.com/71499004/227254549-a167f53c-f0b3-4c82-9d89-016206d5df98.png)

> **Warning**
> This is a very ugly fix for debugging. It's not a general solution!

**Comment by maierbn** [comment]
> All in all, we have that there is a scaling issue due to
> 
>     * the fact the traction depends on the mesh resolution
> 
>     * another scaling factor whose nature  is still unknown to me (what we see in case B)
> 
> 
> @maierbn does this make sense to you or am I understanding traction wrongly? Do you have any idea how to work around the first point and/or ideas for the second point?

Hi @carme-hp, sorry, I'm on vacation this week so it will take some time until I can try it out. Only briefly,
* you're right that the traction vector is in units force per area. This is the common definition in continuum mechanics, you can read about Cauchy's theorem. The traction force between, e.g., car tires and the road is something different.
* About the other factor, I currently don't understand how the load is applied in your figure (free end without external forces?) You probably use conservative mapping which makes sense here?
* That seems strange that everything works if you neglect the x and y directions. Are these contributions coupled correctly, with correct sign? I might also try it out later.

**Comment by carme-hp** [comment]
Thanks for replying! Hope you are enjoying your holidays :smile: 

> About the other factor, I currently don't understand how the load is applied in your figure (free end without external forces?) You probably use conservative mapping which makes sense here?

The tendon participant does not have any boundary conditions specified in `settings_tendon.py`. The only *boundary condition*  comes from precice . I use consistent mapping:
```
      <read-data  name="Traction"      mesh="TendonMeshLeft"/>
      <mapping:nearest-neighbor direction="read" from="MuscleMeshLeft" to="TendonMeshLeft" constraint="consistent"/>
``` 


> That seems strange that everything works if you neglect the x and y directions. Are these contributions coupled correctly, with correct sign? I might also try it out later.

As far as I can tell, there's nothing weird with the signs.  The x,y and z coordinates are multiplied by a factor of -1.

In general what I see is that the muscle writes the materialTraction values to precice, and that the tendon reads the very same values with a factor of (-1), and places them at the right mesh points. Then after reading them, the rhs of the boundary condition is computed, but when I  look at the values of the materialTraction there are some differences.  I think that the differences are too big to be caused by the fact we are using a dynamic solver. 
![image](https://user-images.githubusercontent.com/71499004/227268697-9043f143-1ba0-4e62-b061-b563b1f3e11e.png)

**Comment by carme-hp** [comment]
I think I have to clarify that what my previous plots show.  I plot the average of the z-component of the materialTraction at the interface using the pythonCallback output writer. For example for the tendon I have:

```
    z_traction = get_from_obj(data, [0, 'data', ('name','T (material traction)'), 'components', 2, 'values'])
    [mx, my, mz] = get_from_obj(data, [0, 'nElementsLocal'])
    nx = 2*mx + 1
    ny = 2*my + 1
    nz = 2*mz + 1

    # compute average z-value of begin of muscle
    z_traction_value = 0
    for j in range(ny):
         for i in range(nx):
             z_traction_value += z_traction[ j*nx + i] #muscle: [(nz-1)*nx*ny + j*nx + i]
    z_traction_value /= ny*nx
```

I attach some more plots, where I run the system for a longer time and the difference between the two solvers becomes much bigger. Both solvers use the same resolution and the coupling scheme is explicit.

This time I plot not only for the z-component (which is much larger than the others), but also for the x and y-component. 

![xcoord](https://user-images.githubusercontent.com/71499004/227575980-a564a256-ed7e-4442-b079-967f1ee5a7d0.png)
![ycoord](https://user-images.githubusercontent.com/71499004/227575987-9608d492-b4de-4578-8a2c-4533c89e0544.png)
![zcoord](https://user-images.githubusercontent.com/71499004/227575990-20b52226-44fb-4965-9e5a-148cf51a5a70.png)

I also decided to make a plot without doing the average of the z-component traction over the surface data points for a given time step. This shows a big difference in data points (there is not a global scaling factor). This makes me thing that the data is simply not copied to the right points, even though all I know makes me believe it is.
![points](https://user-images.githubusercontent.com/71499004/227578124-04762347-70e0-4956-96db-77b520b22ee3.png)

**Comment by maierbn** [comment]
OpenDiHu moves to its [new home](https://github.com/opendihu/opendihu) under its own Github Organization :house:. The current repo will be archived soon.

Therefore all issues in the old repo must be closed now, sorry. But you can reopen your issue in the new repo where it will get new attention. :rocket:
