### ISSUE TITLE
Changing write-read direction leads to different results

### ISSUE THREAD

**Issue by carme-hp** [maierbn/opendihu#18]
Until now, the following write-read direction was considered:
![muscle_tendon](https://user-images.githubusercontent.com/71499004/228230968-ec4fc62a-fd81-4569-8136-18b4633ee4ff.png)
But now we also want to support:
![muscle_tendon_reverse](https://user-images.githubusercontent.com/71499004/228231126-c37d8a34-2bb2-4403-9344-ad72beece970.png)

The second option is "unstable" and cannot work using an explicit scheme. The following plot shows the number of iterations needed to satisfy the same convergence criteria for the first option (direct) and the second option (reversed). Note that the maximum number of iterations was 25 in both cases, and it was only achieved at the beginning of the simulation (when the effects of the muscle activation reach the end of the muscle). After that, we have that the reversed option requires a few more iterations, but that's expected behavior. 

![iterations](https://user-images.githubusercontent.com/71499004/228231599-0137303a-c400-47e3-90bb-c588c09cd461.png)

However if we look at the contraction/elongation of the muscle, the results are not good:

![Figure_1](https://user-images.githubusercontent.com/71499004/228233192-cac5e76b-7cb0-415a-86a0-a5a3d17ed1a8.png)

> **Warning**
> The muscle elongates in case of reversed transfer!
> Changing the read-write direction should not affect the results. 
> The simulation explodes before reaching t = 6.0, probably due to nonphysical elongation of the muscle. 

I don't have a reasonable explanation for this issue yet. As pointed out in #15, there is a scaling issue between the traction received by the tendon. Maybe there is also a similar issue when it is the muscle who receives the traction. 

In any case, I have plot the tractions at the two participants as in #15 for comparison purposes. Again, the traction in the plots was multiplied by a factor of (-1).  Interestingly, the tractions seem to be matching (with some scaling) better than in #15. 
![reversex](https://user-images.githubusercontent.com/71499004/228463357-8142a9a5-7ec9-4286-9a80-175e5335fbc2.png)
![reversey](https://user-images.githubusercontent.com/71499004/228463359-105cf7f0-7934-48dd-b17e-e6873f1f156e.png)
![reversez](https://user-images.githubusercontent.com/71499004/228463364-fc4eb7f0-0625-4e6b-83e7-3b623123ea5f.png)

> **Note**
> The z component of traction, the deciding factor for contraction/elongation, is positive in the muscle and negative in the tendon. Is this what we want????

**Comment by maierbn** [comment]
> The z component of traction, the deciding factor for contraction/elongation, is positive in the muscle and negative in the tendon. Is this what we want????

I think yes, consider it a "free-cut", the traction is applied in positive normal direction which is different at the interface between muscle and tendon, `
[0,0,1]` and `[0,0,-1]`.

**Comment by carme-hp** [comment]
**Some more observations for the reversed case** (aka the tendon sends the traction to the muscle):

**The muscle does contract!** However on one node of the muscle-tendon interface we seem to have an outlier. We observe an unreasonable high value of traction, that balances out the contraction of the muscle to the point it leads to elongation.
![outlier_reverse](https://github.com/maierbn/opendihu/assets/71499004/2796b34e-4595-4864-8d57-cdbde2aeb767)


Besides, I observed that **if I fix the free tendon end** instead of fixing the free muscle end, there is also an outlier at a corner node (but not at the same corner!). In that case, the outlier is less prominent and the case runs a bit longer (up to 10ms instead of 7ms)
![outlier_reverse_fixed_tendon](https://github.com/maierbn/opendihu/assets/71499004/ea503030-3cab-4e63-8901-855ec8588c6b)

Same thing **removing the convergence criteria for the traction** (runs up to 10 ms, tendon is fixed again):
![outlier_reverse_fixed_tendon_no_traction](https://github.com/maierbn/opendihu/assets/71499004/b7b6a7e0-a7d5-4790-813c-1e4692090394)


- My first thoughts on this where that maybe we have an outlier because the corresponding node is not correctly integrated in the preCICE faces *2+* and *2-* but after printing the dofs at the faces, I think the node is set correctly. 
- Changing from preCICE faces *2+* and *2-* does no make a difference

**Comment by maierbn** [comment]
OpenDiHu moves to its [new home](https://github.com/opendihu/opendihu) under its own Github Organization :house:. The current repo will be archived soon.

Therefore all issues in the old repo must be closed now, sorry. But you can reopen your issue in the new repo where it will get new attention. :rocket:
