### ISSUE TITLE
Different results when coupling with Opendihu vs coupling with Precice

### ISSUE THREAD

**Issue by silasnatterer** [maierbn/opendihu#20]
We couple the MuscleContractionSolver with the FastMonodomainSolver. 
We use a simple 3x3x9 muscle with Dirichlet boundary conditions on one side and the hodgkin_huxley-razumova CellML.
The solvers are coupled once using the internal Opendihu coupling and once using the PreciceAdapterVolumeCoupling.
Both ways of coupling the solvers produce feasible looking results, but when coupling with Precice the muscle contracts much further:

![Screenshot from 2023-04-25 22-05-16](https://user-images.githubusercontent.com/75208823/234391179-7964115b-18bb-49ad-88e4-e8e801e87ba8.png)

The source code can be found at 
- Opendihu coupling: https://github.tik.uni-stuttgart.de/st168958/bfp/tree/main/muscle_contraction
- Precice coupling: https://github.tik.uni-stuttgart.de/st168958/bfp/tree/main/precice_contraction
- Note that the timestepping parameters used for the picture are different:
dt_3D = 1e-2, dt_splitting = dt_3D/8, dt_1D = dt_splitting, dt_0D = dt_splitting/2, end_time = 25.0
However the problem seems to occur regardless of different timestepping.

**Comment by maierbn** [comment]
My guess is that precice uses an rbf based mapping while opendihu uses a variant of linear interpolation and the mesh size is too coarse to have convergence. Maybe also try varying the radius of the rbf's to see if it has an effect?

**Comment by carme-hp** [comment]
I reproduced the cases and plotted the results on paraview. I use the exact same parameters from the repo, except for the  support radius of the precice mapping, which I set much bigger:

```
     <mapping:rbf-compact-polynomial-c6
        direction="read" 
        from="MuscleContractionMesh" 
        to="FastMonodomainMesh" 
        constraint="consistent" 
        timing="initial" 
	support-radius="10"
     />
```

and 

     <mapping:rbf-compact-polynomial-c6
        direction="read" 
        from="FastMonodomainMesh" 
        to="MuscleContractionMesh" 
        constraint="consistent" 
        timing="initial" 
	support-radius="10"
      />  
    </participant>

This is what I observe:

## Using preCICE OpenDiHu's volume adapter
![with_precice](https://user-images.githubusercontent.com/71499004/235917297-3bb83d1b-60c2-40f9-a731-3b3c68ef0bb2.png)
It looks good!
## Using OpenDiHu's internal coupling feature
![no_precice](https://user-images.githubusercontent.com/71499004/235917349-8601e14f-2e84-4a97-a094-8c3094c472cd.png)
It looks bad! OpenDiHu does not seem able to map for such a coarse fibers mesh. However I can balance it out by making the mesh of the 3D mechanical solver also coarse:

```
el_x, el_y, el_z = 2, 2, 6         
```
![no_precice_coarse_mechanic_mesh](https://user-images.githubusercontent.com/71499004/235917711-b0ea0def-532e-4b04-bdb3-23298f9cf772.png)

A priori, this looks like the muscle contracts equally for the case that uses the preCICE volume adapter and the case that doesn't :smiley:
