### ISSUE TITLE
Unable to execute opendihu on epyc1 cluster via slurm

### ISSUE THREAD

**Issue by ghoshgm** [maierbn/opendihu#28]
First reported by @carme-hp.

OpenDiHu is unable to build or run on epyc1 cluster. After digging through Slurm documentation and ubuntu forums we believe there is a libpmi mismatch. Slurm and MPI may have their own independent libpmi implementation and the documentation says this causes a conflict.

For now there are two ways we can get around this issue:
1. Find the libpmi installation used by slurm on epyc1 and point the MPI installation to it. Probably this will require an independent source build of OpenMPI/MPICH. 
2. Use fresh source build of slurm ,MPI, libpmi and ensure that slurm and MPI point to the same libpmi.

**Comment by IshaanDesai** [comment]
It would be worth checking if this problem exists only for the epyc1 machine or is a problem for any SLURM based compute cluster.

**Comment by ghoshgm** [comment]
@IshaanDesai So far Carme has tested on epyc1 and one other cluster ( I do not remember the name ). The result is always the same.

**Comment by carme-hp** [comment]
Yes,  I have tried it in sgscl1 and epyc-1 cluster. I agree with @ghoshgm  that the problem originates in slurm. 
It works in epyc-2 (no slurm).

**Comment by ghoshgm** [comment]
Did anyone else experience the same issue on epyc1 cluster with different codes ?

**Comment by IshaanDesai** [comment]
It is already good that this is observed for multiple SLURM based systems and not just one. What would be helpful is giving the actual error message or the state where things hang. Also, the original description says *libpmi mistmatch*, but I assume this is meant to be **libmpi mismatch**?

**Comment by ghoshgm** [comment]
There is no typo in the original message. libpmi or the PMIx standard is a low level API which acts as a interface between your application and HPC services like slurm. I understand it can be confusing.
You may refer : https://github.com/pmix/pmix-standard

The error we get is a NULL communicator. For some reason MPI_Init cannot find a valid communicator. What really confuses us is the fact that this happens during compile time. For some configurations the build hangs when it checks for MPI.

Maybe scons is doing something shady in the background, that is also a possibility.

**Comment by IshaanDesai** [comment]
> There is no typo in the original message. libpmi or the PMIx standard is a low level API which acts as a interface between your application and HPC services like slurm. I understand it can be confusing.

Ah okay! That makes much more sense.

One thing I find confusing is that how does preCICE not complain about this if this is really a SLURM and MPI issue, because I compile preCICE with MPI on epyc1 and also use it for parallel runs. Are you certain that OpenDiHu does not ship anything related to MPI by itself and that you are using MPI from a loaded module?

**Comment by ghoshgm** [comment]
> One thing I find confusing is that how does preCICE not complain about this if this is really a SLURM and MPI issue, because I compile preCICE with MPI on epyc1 and also use it for parallel runs. Are you certain that OpenDiHu does not ship anything related to MPI by itself and that you are using MPI from a loaded module?

I see. I was asking for this information on mattermost. At first glance scons always points to the system installation at /usr/bin/x86_64/openmpi. I am assuming when a module is loaded the installation location does not change.

I will make some tests tomorrow.

**Comment by carme-hp** [comment]
### How to build opendihu on epyc 1

1) Create an interactive session on a compute node configuring mpi `srun -n 8 --mpi=pmi2 --pty bash`. Choosing `mpi=cray_shasta`also works.

2) clone opendihu `git clone https://github.com/maierbn/opendihu.git`
3) and build: `make`


If you see the following error message
```
*** An error occurred in MPI_Init
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[ipvs-epyc1:1804875] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
```
Don't kill it, it will still compile and pass all tests :sweat_smile: 

Once you have compiled in an interactive session, you can run your cases using the usual `sbatch` command. Note that even if you want to use one core you'll have to execute your progam with mpirun, eg. `mpirun -n 1 ./muscle ../settings_single_muscle.py`

> **Warning**
> If you need the last version of preCICE, this doesn't work. It only holds for preCICE v2.1

**Comment by ghoshgm** [comment]
This holds true only for scons build system.

**Comment by carme-hp** [comment]
This issue has already been solved. The trick is 
- build OpenDiHu in the ipvs-epyc2 machine 
- run OpenDiHu in either ipvs-epyc1 or ipvs-epyc2

I copy the building instructions for how to setup OpenDiHu in ipvs-epyc2 here:

- Download OpenDiHu: `git clone https://github.com/maierbn/opendihu.git`
- Download input files: Go to https://doi.org/10.5281/zenodo.4705944 and download the `input.tgz` file. Save the file to `opendihu/example/electrophysiology` and extract it (`tar xf input.tgz`)
- Build OpenDiHu: The fastest option is to run `make release_without_tests` in the parent directory. 
- At this point, it should compile corretly, but "Checking for preCICE" will return "no". 
- You need to make PETSc findable to **preCICE v2.5**:
```
export OPENDIHU_HOME=/path/to/opendihu

export PETSC_DIR=$OPENDIHU_HOME/dependencies/petsc/src/petsc-3.12.3
export PETSC_ARCH=arch-linux-c-opt
export LD_LIBRARY_PATH=$OPENDIHU_HOME/dependencies/petsc/install/lib:$OPENDIHU_HOME/dependencies/precice/install/lib
```
- Rebuild preCICE: Run  `scons PRECICE_REBUILD=True`.  Now "Checking for preCICE" will return "yes".

One additional comments: When running you have to use `mpirun` command even if you want to use a single core  `-n 1`. 

For more info you can refer to  #29.
