### ISSUE TITLE
Using opendihu with precice

### ISSUE THREAD

**Issue by carme-hp** [maierbn/opendihu#29]
The documentation has to be updated with the following information:

Disclaimer: This holds for Ubuntu distributions 22.04 and 20.04. 

To use preCICE v2.5 (last available in July 23), please use the [preCICE v2.5 branch]( https://github.com/maierbn/opendihu/tree/update-precice-v2.5). To fullfil preCICE's requirements type:

```
sudo apt update && \
sudo apt install build-essential cmake libeigen3-dev libxml2-dev libboost-all-dev petsc-dev python3-dev python3-numpy
```

Then you can proceed to install OpenDiHu as usual, e.g., run `make`. Note that the difference towards the other branches is that we now don't download petsc but use the existing petsc installation on the system. It's important that previously installed dependencies are removed. 

>**Warning**
> To get rid of installed dependencies you can use `make purge_dependencies`. However this doesn't remove all of them so after that you should run `cd dependencies && rm -rf adios libxml2 opencor std_simd vc xbraid precice`

If for some reason you cannot use `PETSC_DIR=/usr/lib/petsc/` (**for example, if you use ipvs-epyc2**), then modify the user-variables.scons.py as follows:

```
PETSC_DOWNLOAD = True
#PETSC_DIR="/usr/lib/petsc/"
```

Then run `make release_without_tests`. All should compile, but "Checking for preCICE" will return no. Now you can make PETSc findable to preCICE:

```
   export PETSC_DIR=/path/to/opendihu/dependencies/petsc/install
   export PETSC_ARCH=arch-linux-c-opt
```

And then you just have to rebuild preCICE `scons PRECICE_REBUILD=True`. Now "Checking for preCICE" will return yes.

**Comment by ghoshgm** [comment]
You also have to set LD_LIBRARY_PATH for PETSc and preCICE because these two packages are built as shared objects.

**Comment by ghoshgm** [comment]
I am skeptical about the PETSC_ARCH shell variable. This variable points to the PETSc install directory. There are two install directories for PETSc when scons is used. This can cause confusion.

**Comment by ghoshgm** [comment]
Maybe setting the LD_LIBRARY_PATH for precice on epyc1 cluster will fix the missing headers problem.

**Comment by ghoshgm** [comment]
PETSC_DIR should point to the source code directory and not to the install directory.

**Comment by carme-hp** [comment]
Some updates:

The **preCICE v2.5 branch** was merged to **develop**. Meaning that the default branch of OpenDiHu already uses preCICE v2.5 :tada: 
However if you want to use your system petsc installation you need to manually change the `user-variables.scons.py` file as follows:
```
#PETSC_DOWNLOAD = True
PETSC_DIR = "/usr/lib/petsc/"
```

**Comment by carme-hp** [comment]
As @ghoshgm pointed out, the instructions on how to install opendihu in the **ipvs-epyc2** machine were incorrect/incomplete!

### Steps to build OpenDiHu in ipvs-epyc2

- Download OpenDiHu: `git clone https://github.com/maierbn/opendihu.git`
- Download input files: Go to https://doi.org/10.5281/zenodo.4705944 and download the `input.tgz` file. Save the file to `opendihu/example/electrophysiology` and extract it (`tar xf input.tgz`)
- Build OpenDiHu: The fastest option is to run `make release_without_tests` in the parent directory. 
- At this point, it should compile corretly, but "Checking for preCICE" will return "no". 
- You need to make PETSc findable to preCICE:
```
export OPENDIHU_HOME=/path/to/opendihu

export PETSC_DIR=$OPENDIHU_HOME/dependencies/petsc/src/petsc-3.12.3
export PETSC_ARCH=arch-linux-c-opt
export LD_LIBRARY_PATH=$OPENDIHU_HOME/dependencies/petsc/install/lib:$OPENDIHU_HOME/dependencies/precice/install/lib
```
- Rebuild preCICE: Run  `scons PRECICE_REBUILD=True`.  Now "Checking for preCICE" will return "yes".

**Comment by maierbn** [comment]
OpenDiHu moves to its [new home](https://github.com/opendihu/opendihu) under its own Github Organization :house:. The current repo will be archived soon.

Therefore all issues in the old repo must be closed now, sorry. But you can reopen your issue in the new repo where it will get new attention. :rocket:
