### ISSUE TITLE
Manually pointing to Python3.10 in `user-variables.scons.py` fails

### ISSUE THREAD

**Issue by IshaanDesai** [maierbn/opendihu#32]
While building OpenDiHu, instead of allowing it to download Python3.9, I tried to manually point it to the Python3.10 installation on my system. I did this by modifying `user-variables.scons.py` in the following way:

```python
PYTHON_DOWNLOAD = False
PYTHON_INC_DIR = "/usr/include/python3.10"
PYTHON_LIB_DIR = "/usr/lib/python3.10"
```

OpenDiHu finds the include header `Python.h` but fails to find the library files. From the `config.log` it appears that OpenDiHu tries to look for `python3.6m`:

```bash
Beginning check for Python
Found options:
 PYTHON_INC_DIR = ['/usr/include/python3.10']
 PYTHON_LIB_DIR = ['/usr/lib/python3.10']
Trying to find headers in ['/usr/include/python3.10']
Try headers ['Python.h']
 /usr/include/python3.10/Python.h ... yes.
try to compile with one of the following libs: ['python3.6m']
also always try to include one of the following extra libs: [[]]
try library ['python3.6m']
  LIBS:     ['python3.6m', 'petsc', 'mpi_cxx', 'mpi', [], []]
```

which is very puzzling, because I pointed it to Python3.10. Is there a reason that OpenDiHu specifically tries to link to the file `python3.6m`? It does not find this file, because it does not exist, and hence the linking fails.

**Comment by ghoshgm** [comment]
OpenDihu manually changes the path to Python inside the source code. I think that is causing the problem.

**Comment by ghoshgm** [comment]
You will find this at initialize_python.cpp

 //set python home and path, apparently this is not needed
  VLOG(1) << "python home directory: \"" << PYTHON_HOME_DIRECTORY << "\"";
  std::string pythonSearchPath = PYTHON_HOME_DIRECTORY;
  std::string pythonSearchPath = std::string("/store/software/opendihu/dependencies/python/install");
  const wchar_t *pythonSearchPathWChar = Py_DecodeLocale(pythonSearchPath.c_str(), NULL);
  Py_SetPythonHome((wchar_t *)pythonSearchPathWChar);

**Comment by ghoshgm** [comment]
I am still thinking about ways to replace this piece of code.

**Comment by maierbn** [comment]
OpenDiHu moves to its [new home](https://github.com/opendihu/opendihu) under its own Github Organization :house:. The current repo will be archived soon.

Therefore all issues in the old repo must be closed now, sorry. But you can reopen your issue in the new repo where it will get new attention. :rocket:
