### ISSUE TITLE
Unable to run OpenDiHu: MPI_ERR_WIN: invalid window

### ISSUE THREAD

**Issue by carme-hp** [maierbn/opendihu#33]
The following error has been observed:
```
ERROR: core/src/utility/mpi_utility.cpp:45 void MPIUtility::handleReturnValue(int, std::string, MPI_Status): 
Error: Error in MPI_Win_create: MPI_ERR_WIN: invalid window
[lapsgs24:285411] ** An error occurred in MPI_Win_fence
[lapsgs24:285411] * reported by process [1510473729,0]
[lapsgs24:285411] * on communicator MPI_COMM_WORLD
[lapsgs24:285411] * MPI_ERR_WIN: invalid window
[lapsgs24:285411] * MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[lapsgs24:285411] ***    and potentially your MPI job)
```
To my knowledge this is a system-specific error: I've observe it on Ubuntu 22.04 machines. 

This can be fixed by adding `export OMPI_MCA_osc="^ucx"` to your bashrc file.

**Comment by ghoshgm** [comment]
@carme-hp Did you check the MPI version ? The latest versions can be buggy.

**Comment by carme-hp** [comment]
In my laptop (Ubuntu 22 with Open MPI 4.1.2) I had to add `export OMPI_MCA_osc="^ucx"`.

I also have installed OpenDIHU using Ubuntu 20 and Open MPI 4.0.3: there `export OMPI_MCA_osc="^ucx"` was not needed.

In any case, I cannot make any claims about for which MPI versions the issue appears, as until now I just collected the Ubuntu distribution information.

**Comment by carme-hp** [comment]
I close the issue, as it is already mentioned in the [documentation](https://opendihu.readthedocs.io/en/latest/user/installation.html).
