### ISSUE TITLE
CMake build freezes when creating a shared pointer.

### ISSUE THREAD

**Issue by ghoshgm** [maierbn/opendihu#34]
I have integrated CMake into OpenDihu and currently I am testing it.

I observed that when run the examples using MPI ( 2 ranks or more ) it freezes at this line:

`std::shared_ptr<FieldVariable::FieldVariable<FunctionSpace<MeshType,BasisFunctionType>,nComponents>> fieldVariable
    = std::make_shared<FieldVariable::FieldVariable<FunctionSpace<MeshType,BasisFunctionType>,nComponents>>(this->geometryField(), name, componentNames);
`
It is highly improbable that std::shared_pointer is the issue. Maybe the constructor of the template type causes problems. However, I cannot find the constructor in the source code.

**Comment by maierbn** [comment]
OpenDiHu moves to its [new home](https://github.com/opendihu/opendihu) under its own Github Organization :house:. The current repo will be archived soon.

Therefore all issues in the old repo must be closed now, sorry. But you can reopen your issue in the new repo where it will get new attention. :rocket:
