### ISSUE TITLE
Memory leaks with OpenMPI

### ISSUE THREAD

**Issue by ghoshgm** [maierbn/opendihu#45]
I discovered memory leaks when using valgrind on opendihu. On close observation OpenMPI has some quirky behavior which leads to false-positive results. However, the documentation mentions the MPI_Finalize() does not free memory properly in some cases. You may refer the last section in the link below:
https://www.open-mpi.org/faq/?category=debugging#valgrind_clean

Valgrind does not generate false-positives when MPICH is used. I am more inclined towards using MPICH because it is more stable and the community claims it is more optimized than OpenMPI.

**Comment by maierbn** [comment]
OpenDiHu moves to its [new home](https://github.com/opendihu/opendihu) under its own Github Organization :house:. The current repo will be archived soon.

Therefore all issues in the old repo must be closed now, sorry. But you can reopen your issue in the new repo where it will get new attention. :rocket:
