### ISSUE TITLE
Bug: Unable to download PETSc

### ISSUE THREAD

**Issue by carme-hp** [maierbn/opendihu#47]
Hi,

Since today, I was not able to build OpenDiHu.  After running
```
git checkout develop
make purge_dependencies
make release_without_tests
```
I encounter an error:
> scons: Reading SConscript files ...
Checking for MPI ...           (cached) yes
Checking for PETSc ...         
  Downloading ... failed.
HTTP Error 403: Forbidden
failed.

My first thought was that the download link for petsc is obsolete, but `wget http://ftp.mcs.anl.gov/pub/petsc/release-snapshots/petsc-lite-3.15.5.tar.gz` worked well. 

I tried in a different system and the same error occurred. Any ideas?

**Comment by Conni2461** [comment]
i am also experiencing this and also tried to replace the `tar.gz` link (i reinstalled thhe scons-config dist), without any success.

i am currently working around this issue by manually downloading the `petsc-lite-3.15.5.tar.gz` file into `petsc-lite-3.15.5.tar.gz`

**Comment by Conni2461** [comment]
This link seems to work: https://web.cels.anl.gov/projects/petsc/download/release-snapshots/petsc-lite-3.15.5.tar.gz

**Comment by carme-hp** [comment]
I tried your link and you are right, this one seems to work. 
I will just update the link, there was no specific reason to choose the former link.
